const express = require('express');
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const tableRoutes = require('./table.routes');
const reservationRoutes = require('./reservation.routes');
const orderRoutes = require('./order.routes');
const productRoutes = require('./product.routes');
const categoryRoutes = require('./category.routes');
const offerRoutes = require('./offer.routes');
const couponRoutes = require('./coupon.routes');
const customerRoutes = require('./customer.routes');
const subscriptionRoutes = require('./subscription.routes');
const financialRoutes = require('./financial.routes');
const shiftRoutes = require('./shift.routes');
const kitchenRoutes = require('./kitchen.routes');
const reportRoutes = require('./report.routes');
const locationRoutes = require('./location.routes');
const supplierRoutes = require('./supplier.routes');
const notificationRoutes = require('./notification.routes');
const inventoryRoutes = require('./inventory.routes');
const reviewRoutes = require('./review.routes');
const warehouseRoutes = require('./warehouse.routes');
const purchasingRoutes = require('./purchasing.routes');
const pricingRoutes = require('./pricing.routes');
const productionRoutes = require('./production.routes');
const logisticsRoutes = require('./logistics.routes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/tables', tableRoutes);
router.use('/reservations', reservationRoutes);
router.use('/orders', orderRoutes);
router.use('/products', productRoutes);
router.use('/categories', categoryRoutes);
router.use('/offers', offerRoutes);
router.use('/coupons', couponRoutes);
router.use('/customers', customerRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/financial', financialRoutes);
router.use('/pos', shiftRoutes);
router.use('/kitchen', kitchenRoutes);
router.use('/reports', reportRoutes);
router.use('/locations', locationRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/notifications', notificationRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/reviews', reviewRoutes);
router.use('/warehouses', warehouseRoutes);
router.use('/purchasing', purchasingRoutes);
router.use('/pricing', pricingRoutes);
router.use('/production', productionRoutes);
router.use('/logistics', logisticsRoutes);

module.exports = router;
